db.Restaurants.find()
db.Restaurants.find({}, {restaurant_id: 1, borough: 1, cuisine: 1})
db.Restaurants.find({}, {restaurant_id: 1, borough: 1, cuisine: 1, _id: 0})
db.Restaurants.find({}, {restaurant_id: 1, borough: 1, cuisine: 1, zip_code: 1, _id: 0})
db.Restaurants.find({borough: "Bronx"})
db.Restaurants.find({borough: "Bronx"}).sort({_id: 1}).limit(5)
db.Restaurants.find({borough: "Bronx"}).sort({_id: 1}).skip(5).limit(5)
db.Restaurants.find({"grades.score": {$gt: 90}})
db.Restaurants.find({grades: {$elemMatch: {score: {$gt: 80, $lt: 100}}}})
db.restaurant.find({grades: {$elemMatch: {score: {$gt: 80, $lt: 100} }}}) // db.Restaurants.find({"grades.score": {$gt: 80, $lt: 500}})
db.Restaurants.find({"address.coord.0": {$lt: -95.754168}})
db.Restaurants.find({$and:[{cuisine: {$not: {$eq:"American"}}}, {grades: {$elemMatch: {score: {$gt: 70}}}}, {"address.coord.0": {$lt: -65.754168}}]})
